export default [
  {
    code: 'Backquote',
    key: '`',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '~',
  },
  {
    code: 'Digit1',
    key: '1',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '!',
  },
  {
    code: 'Digit2',
    key: '2',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '@',
  },
  {
    code: 'Digit3',
    key: '3',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '#',
  },
  {
    code: 'Digit4',
    key: '4',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '$',
  },
  {
    code: 'Digit5',
    key: '5',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '%',
  },
  {
    code: 'Digit6',
    key: '6',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '^',
  },
  {
    code: 'Digit7',
    key: '7',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '&',
  },
  {
    code: 'Digit8',
    key: '8',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '*',
  },
  {
    code: 'Digit9',
    key: '9',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '(',
  },
  {
    code: 'Digit0',
    key: '0',
    size: 'standard',
    type: 'text',
    shiftAnalogue: ')',
  },
  {
    code: 'Minus',
    key: '-',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '_',
  },
  {
    code: 'Equal',
    key: '=',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '+',
  },
  {
    code: 'Backspace',
    key: 'Backspace',
    size: 'wide',
    type: 'control',
  },
  {
    code: 'Tab',
    key: 'Tab',
    size: 'medium',
    type: 'control',
  },
  {
    code: 'KeyQ',
    key: 'q',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyW',
    key: 'w',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyE',
    key: 'e',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyR',
    key: 'r',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyT',
    key: 't',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyY',
    key: 'y',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyU',
    key: 'u',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyI',
    key: 'i',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyO',
    key: 'o',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyP',
    key: 'p',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'BracketLeft',
    key: '[',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '{',
  },
  {
    code: 'BracketRight',
    key: ']',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '}',
  },
  {
    code: 'Backslash',
    key: '\\',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '|',
  },
  {
    code: 'Delete',
    key: 'Del',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'CapsLock',
    key: 'CapsLock',
    size: 'double',
    type: 'control',
  },
  {
    code: 'KeyA',
    key: 'a',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyS',
    key: 's',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyD',
    key: 'd',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyF',
    key: 'f',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyG',
    key: 'g',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyH',
    key: 'h',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyJ',
    key: 'j',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyK',
    key: 'k',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyL',
    key: 'l',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'Semicolon',
    key: ';',
    size: 'standard',
    type: 'text',
    shiftAnalogue: ':',
  },
  {
    code: 'Quote',
    key: "'",
    size: 'standard',
    type: 'text',
    shiftAnalogue: '"',
  },
  {
    code: 'Enter',
    key: 'Enter',
    size: 'wide',
    type: 'control',
  },
  {
    code: 'ShiftLeft',
    key: 'Shift',
    size: 'wide',
    type: 'control',
  },
  {
    code: 'KeyZ',
    key: 'z',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyX',
    key: 'x',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyC',
    key: 'c',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyV',
    key: 'v',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyB',
    key: 'b',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyN',
    key: 'n',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'KeyM',
    key: 'm',
    size: 'standard',
    type: 'text',
  },
  {
    code: 'Comma',
    key: ',',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '<',
  },
  {
    code: 'Period',
    key: '.',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '>',
  },
  {
    code: 'Slash',
    key: '/',
    size: 'standard',
    type: 'text',
    shiftAnalogue: '?',
  },
  {
    code: 'ArrowUp',
    key: '▲',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'ShiftRight',
    key: 'Shift',
    size: 'double',
    type: 'control',
  },
  {
    code: 'ControlLeft',
    key: 'Ctrl',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'MetaLeft',
    key: 'Win',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'Language',
    key: '🌐',
    size: 'standard',
    type: 'lang',
  },
  {
    code: 'AltLeft',
    key: 'Alt',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'Space',
    key: ' ',
    size: 'space',
    type: 'control',
  },
  {
    code: 'AltRight',
    key: 'Alt',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'ArrowLeft',
    key: '◀',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'ArrowDown',
    key: '▼',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'ArrowRight',
    key: '▶',
    size: 'standard',
    type: 'control',
  },
  {
    code: 'ControlRight',
    key: 'Ctrl',
    size: 'standard',
    type: 'control',
  },
];
